apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oza3ki3hv-go
  janus-idp.io/tekton: oza3ki3hv-go
  backstage.io/kubernetes-id: oza3ki3hv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oza3ki3hv-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
