apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oza3ki3hv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oza3ki3hv-go 
  name: oza3ki3hv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oza3ki3hv-go 
